### ISSUE TITLE
Provide previews and/or binary releases of the flutter app

### ISSUE THREAD

**Issue by wh201906** [GlitchPunkWTF/edifier-proto#1]
Hi. Thank you for creating this app!
Would you like to add some previews in the README and/or add the binary releases in the repo? I think it's convenient for users to know what the app can provide without building it on their machine.

**Comment by glpnk** [comment]
Sorry but I just use debug release with random signature, maybe later I`m add actions build

**Comment by glpnk** [comment]
I have already added the [release apk](https://github.com/GlitchPunkWTF/edifier-proto/releases/download/v0.1.0/app.apk) and forgot about it

**Comment by wh201906** [comment]
Thanks
