### ISSUE TITLE
Noise cancellation usb control

### ISSUE THREAD

**Issue by Letus252** [GlitchPunkWTF/edifier-proto#2]
Hey. Thanks for making this script. I have one question. I want to be able to turn off noise cancellation on my Edifier W820NB Plus headphones. Since my PC doesn't have Bluetooth, I decided to connect the headphones via USB-C. There is only one problem: by default, the button on the side of the headphones can only switch between noise cancellation on and ambient sound; there is no way to just turn off noise cancellation. You can change that in the Edifier app, but as soon as you connect the headphones to power, this setting resets. And, since there isn't any Edifier app for PC, I'm unable to use these headphones without noise cancellation (or ambient sound mode). My question is, could you make a script/command that would allow me to turn off noise cancellation via USB-C, or maybe do you know a way to prevent the reset of an option that adds the ability to turn off noise cancellation via the button? I tried doing it myself, but since I'm not a programmer, and the task seems to be very hard, I just don't know how. If you can't, at least tell me if it's possible. Thanks.

**Comment by glpnk** [comment]
Main discussion here: https://github.com/wh201906/mEDIFIER/issues/3
